# Dataset Generation

In [29]:
from skmultiflow.data import SEAGenerator 
import numpy as np

In [19]:
stream = SEAGenerator()

In [26]:
stream.get_data_info()

'SEA Generator - 1 target(s), 2 classes, 3 features'

In [21]:
stream.n_remaining_samples()

-1

In [22]:
test = stream.next_sample(100000)

In [23]:
test

(array([[6.57257899, 0.32145007, 2.41677593],
        [0.86367974, 8.2420766 , 1.02867418],
        [3.20783494, 6.80917952, 4.63883083],
        ...,
        [1.06262852, 4.91352683, 8.17472851],
        [0.85150685, 1.11278679, 1.99144859],
        [1.58034651, 0.07312384, 0.35317229]]),
 array([0, 1, 1, ..., 0, 0, 0]))

In [24]:
stream.generate_drift()

In [25]:
stream.next_sample(100000)

(array([[4.4050243 , 4.79051383, 1.00290631],
        [7.57237744, 3.96371858, 4.99637722],
        [9.99752228, 1.67677742, 8.14997491],
        ...,
        [3.0601149 , 1.81770352, 1.68315029],
        [5.57241323, 1.14851599, 9.22016065],
        [3.79080183, 1.43653961, 8.58163715]]),
 array([0, 1, 1, ..., 0, 0, 0]))

In [27]:
stream.get_info()

'SEAGenerator(balance_classes=False, classification_function=3,\n             noise_percentage=0.0, random_state=None)'

In [55]:
np.column_stack((test[0],test[1]) )

array([[6.57257899, 0.32145007, 2.41677593, 0.        ],
       [0.86367974, 8.2420766 , 1.02867418, 1.        ],
       [3.20783494, 6.80917952, 4.63883083, 1.        ],
       ...,
       [1.06262852, 4.91352683, 8.17472851, 0.        ],
       [0.85150685, 1.11278679, 1.99144859, 0.        ],
       [1.58034651, 0.07312384, 0.35317229, 0.        ]])